name: Guardian
version: 0.1
description: Bukkit plugin to automatically group bPermissions users when they enter a password
author: md_5
website: https://github.com/md-5/Vote4Diamndz

main: org.guardian.Guardian