name: Guardian
version: ${build.number}
description: The future of griefer tracking and rollback for Bukkit
authors: [DiddiZ, md_5, oliverw92]
website: https://github.com/Guardian-Security/Guardian

main: org.guardian.Guardian
softdepend: [Spout, WorldEdit]

commands:
    guardian:
        description: Access to the main Guardian command
        aliases: gd
        permission: guardian.command 

permissions:
    guardian.clearlog:
        description: The ability to clear Guardian logs
        default: op
    guardian.command:
        description: Allows the user to see Guardian
        default: true
    guardian.lookup:
        description: Allows the looking up of events
        default: op
    guardian.redo:
        description: The ability to redo an undone rollback
        default: op
    guardian.rollback:
        description: Allows the rollbacking of events
        default: op
    guardian.see:
        description: The ability to sense Guardians presence when in ninja mode
        default: op
    guardian.undo:
        description: The ability to undo a rollback
        default: op
    guardian.writelog:
        description: The ability to write a log based on the previous rollback
        default: op